[package]
name = "duid-engine"
version = "0.1.0"
edition = "2021"


[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
tracing = { version = "0.1", features = ["log"] }
console_log = "1.0.0"


[profile.release]
debug = true
lto = true