[package]
name = "duid-app"
version = "0.1.0"
edition = "2021"


[dependencies]
duid-core = {version = "0.1.0", path = "./duid-core"}

[workspace]
members = [
    "duid-core",
    "duid-data-grid",
    "duid-ui"
]

exclude = [
    "duid-engine",
    "duid-design",
    "duid-integrations/duid-core-test"
]