[package]
name = "duid-app"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "cargo-duid-app"
path = "./cargo-duid-app"


[dependencies]


[workspace]
members = [
    "cargo-duid-app",
    "duid-core",
    "duid-data-grid",
    "duid-ui"
]

exclude = [
    "duid-design",
    "duid-integration",
    "djed-test"
]