use std::collections::HashMap;


pub(crate) fn gap() -> HashMap<String, String> {
    let mut gap = HashMap::new();
    let _ = gap.insert("gap-0".to_owned(), "gap: 0px;".to_owned());
    let _ = gap.insert("gap-x-0".to_owned(), "column-gap: 0px;".to_owned());
    let _ = gap.insert("gap-y-0".to_owned(), "row-gap: 0px;".to_owned());
    let _ = gap.insert("gap-px".to_owned(), "gap: 1px;".to_owned());
    let _ = gap.insert("gap-x-px".to_owned(), "column-gap: 1px;".to_owned());
    let _ = gap.insert("gap-y-px".to_owned(), "row-gap: 1px;".to_owned());
    let _ = gap.insert("gap-0.5".to_owned(), "gap: 0.125rem;".to_owned()); /* 2px */
    let _ = gap.insert("gap-x-0.5".to_owned(), "column-gap: 0.125rem;".to_owned()); /* 2px */
    let _ = gap.insert("gap-y-0.5".to_owned(), "row-gap: 0.125rem;".to_owned()); /* 2px */
    let _ = gap.insert("gap-1".to_owned(), "gap: 0.25rem;".to_owned()); /* 4px */
    let _ = gap.insert("gap-x-1".to_owned(), "column-gap: 0.25rem;".to_owned()); /* 4px */
    let _ = gap.insert("gap-y-1".to_owned(), "row-gap: 0.25rem;".to_owned()); /* 4px */
    let _ = gap.insert("gap-1.5".to_owned(), "gap: 0.375rem;".to_owned()); /* 6px */
    let _ = gap.insert("gap-x-1.5".to_owned(), "column-gap: 0.375rem;".to_owned()); /* 6px */
    let _ = gap.insert("gap-y-1.5".to_owned(), "row-gap: 0.375rem;".to_owned()); /* 6px */
    let _ = gap.insert("gap-2".to_owned(), "gap: 0.5rem;".to_owned()); /* 8px */
    let _ = gap.insert("gap-x-2".to_owned(), "column-gap: 0.5rem;".to_owned()); /* 8px */
    let _ = gap.insert("gap-y-2".to_owned(), "row-gap: 0.5rem;".to_owned()); /* 8px */
    let _ = gap.insert("gap-2.5".to_owned(), "gap: 0.625rem;".to_owned()); /* 10px */
    let _ = gap.insert("gap-x-2.5".to_owned(), "column-gap: 0.625rem;".to_owned()); /* 10px */
    let _ = gap.insert("gap-y-2.5".to_owned(), "row-gap: 0.625rem;".to_owned()); /* 10px */
    let _ = gap.insert("gap-3".to_owned(), "gap: 0.75rem;".to_owned()); /* 12px */
    let _ = gap.insert("gap-x-3".to_owned(), "column-gap: 0.75rem;".to_owned()); /* 12px */
    let _ = gap.insert("gap-y-3".to_owned(), "row-gap: 0.75rem;".to_owned()); /* 12px */
    let _ = gap.insert("gap-3.5".to_owned(), "gap: 0.875rem;".to_owned()); /* 14px */
    let _ = gap.insert("gap-x-3.5".to_owned(), "column-gap: 0.875rem;".to_owned()); /* 14px */
    let _ = gap.insert("gap-y-3.5".to_owned(), "row-gap: 0.875rem;".to_owned()); /* 14px */
    let _ = gap.insert("gap-4".to_owned(), "gap: 1rem;".to_owned()); /* 16px */
    let _ = gap.insert("gap-x-4".to_owned(), "column-gap: 1rem;".to_owned()); /* 16px */
    let _ = gap.insert("gap-y-4".to_owned(), "row-gap: 1rem;".to_owned()); /* 16px */
    let _ = gap.insert("gap-5".to_owned(), "gap: 1.25rem;".to_owned()); /* 20px */
    let _ = gap.insert("gap-x-5".to_owned(), "column-gap: 1.25rem;".to_owned()); /* 20px */
    let _ = gap.insert("gap-y-5".to_owned(), "row-gap: 1.25rem;".to_owned()); /* 20px */
    let _ = gap.insert("gap-6".to_owned(), "gap: 1.5rem;".to_owned()); /* 24px */
    let _ = gap.insert("gap-x-6".to_owned(), "column-gap: 1.5rem;".to_owned()); /* 24px */
    let _ = gap.insert("gap-y-6".to_owned(), "row-gap: 1.5rem;".to_owned()); /* 24px */
    let _ = gap.insert("gap-7".to_owned(), "gap: 1.75rem;".to_owned()); /* 28px */
    let _ = gap.insert("gap-x-7".to_owned(), "column-gap: 1.75rem;".to_owned()); /* 28px */
    let _ = gap.insert("gap-y-7".to_owned(), "row-gap: 1.75rem;".to_owned()); /* 28px */
    let _ = gap.insert("gap-8".to_owned(), "gap: 2rem;".to_owned()); /* 32px */
    let _ = gap.insert("gap-x-8".to_owned(), "column-gap: 2rem;".to_owned()); /* 32px */
    let _ = gap.insert("gap-y-8".to_owned(), "row-gap: 2rem;".to_owned()); /* 32px */
    let _ = gap.insert("gap-9".to_owned(), "gap: 2.25rem;".to_owned()); /* 36px */
    let _ = gap.insert("gap-x-9".to_owned(), "column-gap: 2.25rem;".to_owned()); /* 36px */
    let _ = gap.insert("gap-y-9".to_owned(), "row-gap: 2.25rem;".to_owned()); /* 36px */
    let _ = gap.insert("gap-10".to_owned(), "gap: 2.5rem;".to_owned()); /* 40px */
    let _ = gap.insert("gap-x-10".to_owned(), "column-gap: 2.5rem;".to_owned()); /* 40px */
    let _ = gap.insert("gap-y-10".to_owned(), "row-gap: 2.5rem;".to_owned()); /* 40px */
    let _ = gap.insert("gap-11".to_owned(), "gap: 2.75rem;".to_owned()); /* 44px */
    let _ = gap.insert("gap-x-11".to_owned(), "column-gap: 2.75rem;".to_owned()); /* 44px */
    let _ = gap.insert("gap-y-11".to_owned(), "row-gap: 2.75rem;".to_owned()); /* 44px */
    let _ = gap.insert("gap-12".to_owned(), "gap: 3rem;".to_owned()); /* 48px */
    let _ = gap.insert("gap-x-12".to_owned(), "column-gap: 3rem;".to_owned()); /* 48px */
    let _ = gap.insert("gap-y-12".to_owned(), "row-gap: 3rem;".to_owned()); /* 48px */
    let _ = gap.insert("gap-14".to_owned(), "gap: 3.5rem;".to_owned()); /* 56px */
    let _ = gap.insert("gap-x-14".to_owned(), "column-gap: 3.5rem;".to_owned()); /* 56px */
    let _ = gap.insert("gap-y-14".to_owned(), "row-gap: 3.5rem;".to_owned()); /* 56px */
    let _ = gap.insert("gap-16".to_owned(), "gap: 4rem;".to_owned()); /* 64px */
    let _ = gap.insert("gap-x-16".to_owned(), "column-gap: 4rem;".to_owned()); /* 64px */
    let _ = gap.insert("gap-y-16".to_owned(), "row-gap: 4rem;".to_owned()); /* 64px */
    let _ = gap.insert("gap-20".to_owned(), "gap: 5rem;".to_owned()); /* 80px */
    let _ = gap.insert("gap-x-20".to_owned(), "column-gap: 5rem;".to_owned()); /* 80px */
    let _ = gap.insert("gap-y-20".to_owned(), "row-gap: 5rem;".to_owned()); /* 80px */
    let _ = gap.insert("gap-24".to_owned(), "gap: 6rem;".to_owned()); /* 96px */
    let _ = gap.insert("gap-x-24".to_owned(), "column-gap: 6rem;".to_owned()); /* 96px */
    let _ = gap.insert("gap-y-24".to_owned(), "row-gap: 6rem;".to_owned()); /* 96px */
    let _ = gap.insert("gap-28".to_owned(), "gap: 7rem;".to_owned()); /* 112px */
    let _ = gap.insert("gap-x-28".to_owned(), "column-gap: 7rem;".to_owned()); /* 112px */
    let _ = gap.insert("gap-y-28".to_owned(), "row-gap: 7rem;".to_owned()); /* 112px */
    let _ = gap.insert("gap-32".to_owned(), "gap: 8rem;".to_owned()); /* 128px */
    let _ = gap.insert("gap-x-32".to_owned(), "column-gap: 8rem;".to_owned()); /* 128px */
    let _ = gap.insert("gap-y-32".to_owned(), "row-gap: 8rem;".to_owned()); /* 128px */
    let _ = gap.insert("gap-36".to_owned(), "gap: 9rem;".to_owned()); /* 144px */
    let _ = gap.insert("gap-x-36".to_owned(), "column-gap: 9rem;".to_owned()); /* 144px */
    let _ = gap.insert("gap-y-36".to_owned(), "row-gap: 9rem;".to_owned()); /* 144px */
    let _ = gap.insert("gap-40".to_owned(), "gap: 10rem;".to_owned()); /* 160px */
    let _ = gap.insert("gap-x-40".to_owned(), "column-gap: 10rem;".to_owned()); /* 160px */
    let _ = gap.insert("gap-y-40".to_owned(), "row-gap: 10rem;".to_owned()); /* 160px */
    let _ = gap.insert("gap-44".to_owned(), "gap: 11rem;".to_owned()); /* 176px */
    let _ = gap.insert("gap-x-44".to_owned(), "column-gap: 11rem;".to_owned()); /* 176px */
    let _ = gap.insert("gap-y-44".to_owned(), "row-gap: 11rem;".to_owned()); /* 176px */
    let _ = gap.insert("gap-48".to_owned(), "gap: 12rem;".to_owned()); /* 192px */
    let _ = gap.insert("gap-x-48".to_owned(), "column-gap: 12rem;".to_owned()); /* 192px */
    let _ = gap.insert("gap-y-48".to_owned(), "row-gap: 12rem;".to_owned()); /* 192px */
    let _ = gap.insert("gap-52".to_owned(), "gap: 13rem;".to_owned()); /* 208px */
    let _ = gap.insert("gap-x-52".to_owned(), "column-gap: 13rem;".to_owned()); /* 208px */
    let _ = gap.insert("gap-y-52".to_owned(), "row-gap: 13rem;".to_owned()); /* 208px */
    let _ = gap.insert("gap-56".to_owned(), "gap: 14rem;".to_owned()); /* 224px */
    let _ = gap.insert("gap-x-56".to_owned(), "column-gap: 14rem;".to_owned()); /* 224px */
    let _ = gap.insert("gap-y-56".to_owned(), "row-gap: 14rem;".to_owned()); /* 224px */
    let _ = gap.insert("gap-60".to_owned(), "gap: 15rem;".to_owned()); /* 240px */
    let _ = gap.insert("gap-x-60".to_owned(), "column-gap: 15rem;".to_owned()); /* 240px */
    let _ = gap.insert("gap-y-60".to_owned(), "row-gap: 15rem;".to_owned()); /* 240px */
    let _ = gap.insert("gap-64".to_owned(), "gap: 16rem;".to_owned()); /* 256px */
    let _ = gap.insert("gap-x-64".to_owned(), "column-gap: 16rem;".to_owned()); /* 256px */
    let _ = gap.insert("gap-y-64".to_owned(), "row-gap: 16rem;".to_owned()); /* 256px */
    let _ = gap.insert("gap-72".to_owned(), "gap: 18rem;".to_owned()); /* 288px */
    let _ = gap.insert("gap-x-72".to_owned(), "column-gap: 18rem;".to_owned()); /* 288px */
    let _ = gap.insert("gap-y-72".to_owned(), "row-gap: 18rem;".to_owned()); /* 288px */
    let _ = gap.insert("gap-80".to_owned(), "gap: 20rem;".to_owned()); /* 320px */
    let _ = gap.insert("gap-x-80".to_owned(), "column-gap: 20rem;".to_owned()); /* 320px */
    let _ = gap.insert("gap-y-80".to_owned(), "row-gap: 20rem;".to_owned()); /* 320px */
    let _ = gap.insert("gap-96".to_owned(), "gap: 24rem;".to_owned()); /* 384px */
    let _ = gap.insert("gap-x-96".to_owned(), "column-gap: 24rem;".to_owned()); /* 384px */
    let _ = gap.insert("gap-y-96".to_owned(), "row-gap: 24rem;".to_owned()); /* 384px */
    
    gap
}