use std::collections::HashMap;


pub(crate) fn border_radius() -> HashMap<String, String> {
    let mut border_radius = HashMap::new();
    let _ = border_radius.insert("rounded-none".to_owned(), "border-radius: 0px;".to_owned());
    let _ = border_radius.insert("rounded-sm".to_owned(), "border-radius: 0.125rem;".to_owned()); /* 2px */
    let _ = border_radius.insert("rounded".to_owned(), "border-radius: 0.25rem;".to_owned()); /* 4px */
    let _ = border_radius.insert("rounded-md".to_owned(), "border-radius: 0.375rem;".to_owned()); /* 6px */
    let _ = border_radius.insert("rounded-lg".to_owned(), "border-radius: 0.5rem;".to_owned()); /* 8px */
    let _ = border_radius.insert("rounded-xl".to_owned(), "border-radius: 0.75rem;".to_owned()); /* 12px */
    let _ = border_radius.insert("rounded-2xl".to_owned(), "border-radius: 1rem;".to_owned()); /* 16px */
    let _ = border_radius.insert("rounded-3xl".to_owned(), "border-radius: 1.5rem;".to_owned()); /* 24px */
    let _ = border_radius.insert("rounded-full".to_owned(), "border-radius: 9999px;".to_owned());
    let _ = border_radius.insert("rounded-t-none".to_owned(), "border-top-left-radius: 0px;border-top-right-radius: 0px;".to_owned());
    let _ = border_radius.insert("rounded-t-sm".to_owned(), "border-top-left-radius: 0.125rem;border-top-right-radius: 0.125rem;".to_owned()); /* 2px */
    let _ = border_radius.insert("rounded-t".to_owned(), "border-top-left-radius: 0.25rem;border-top-right-radius: 0.25rem;".to_owned()); /* 4px */
    let _ = border_radius.insert("rounded-t-md".to_owned(), "border-top-left-radius: 0.375rem;border-top-right-radius: 0.375rem;".to_owned()); /* 6px */
    let _ = border_radius.insert("rounded-t-lg".to_owned(), "border-top-left-radius: 0.5rem;border-top-right-radius: 0.5rem;".to_owned()); /* 8px */
    let _ = border_radius.insert("rounded-t-xl".to_owned(), "border-top-left-radius: 0.75rem;border-top-right-radius: 0.75rem;".to_owned()); /* 12px */
    let _ = border_radius.insert("rounded-t-2xl".to_owned(), "border-top-left-radius: 1rem;border-top-right-radius: 1rem;".to_owned()); /* 16px */
    let _ = border_radius.insert("rounded-t-3xl".to_owned(), "border-top-left-radius: 1.5rem;border-top-right-radius: 1.5rem;".to_owned()); /* 24px */
    let _ = border_radius.insert("rounded-t-full".to_owned(), "border-top-left-radius: 9999px;border-top-right-radius: 9999px;".to_owned());
    let _ = border_radius.insert("rounded-r-none".to_owned(), "border-top-right-radius: 0px;border-bottom-right-radius: 0px;".to_owned());
    let _ = border_radius.insert("rounded-r-sm".to_owned(), "border-top-right-radius: 0.125rem;border-bottom-right-radius: 0.125rem;".to_owned()); /* 2px */
    let _ = border_radius.insert("rounded-r".to_owned(), "border-top-right-radius: 0.25rem;border-bottom-right-radius: 0.25rem;".to_owned()); /* 4px */
    let _ = border_radius.insert("rounded-r-md".to_owned(), "border-top-right-radius: 0.375rem;border-bottom-right-radius: 0.375rem;".to_owned()); /* 6px */
    let _ = border_radius.insert("rounded-r-lg".to_owned(), "border-top-right-radius: 0.5rem;border-bottom-right-radius: 0.5rem;".to_owned()); /* 8px */
    let _ = border_radius.insert("rounded-r-xl".to_owned(), "border-top-right-radius: 0.75rem;border-bottom-right-radius: 0.75rem;".to_owned()); /* 12px */
    let _ = border_radius.insert("rounded-r-2xl".to_owned(), "border-top-right-radius: 1rem;border-bottom-right-radius: 1rem;".to_owned()); /* 16px */
    let _ = border_radius.insert("rounded-r-3xl".to_owned(), "border-top-right-radius: 1.5rem;border-bottom-right-radius: 1.5rem;".to_owned()); /* 24px */
    let _ = border_radius.insert("rounded-r-full".to_owned(), "border-top-right-radius: 9999px;border-bottom-right-radius: 9999px;".to_owned());
    let _ = border_radius.insert("rounded-b-none".to_owned(), "border-bottom-right-radius: 0px;border-bottom-left-radius: 0px;".to_owned());
    let _ = border_radius.insert("rounded-b-sm".to_owned(), "border-bottom-right-radius: 0.125rem;order-bottom-left-radius: 0.125rem;".to_owned()); /* 2px */
    let _ = border_radius.insert("rounded-b".to_owned(), "border-bottom-right-radius: 0.25rem;order-bottom-left-radius: 0.25rem;".to_owned()); /* 4px */
    let _ = border_radius.insert("rounded-b-md".to_owned(), "border-bottom-right-radius: 0.375rem;order-bottom-left-radius: 0.375rem;".to_owned()); /* 6px */
    let _ = border_radius.insert("rounded-b-lg".to_owned(), "border-bottom-right-radius: 0.5rem;order-bottom-left-radius: 0.5rem;".to_owned()); /* 8px */
    let _ = border_radius.insert("rounded-b-xl".to_owned(), "border-bottom-right-radius: 0.75rem;order-bottom-left-radius: 0.75rem;".to_owned()); /* 12px */
    let _ = border_radius.insert("rounded-b-2xl".to_owned(), "border-bottom-right-radius: 1rem;order-bottom-left-radius: 1rem;".to_owned()); /* 16px */
    let _ = border_radius.insert("rounded-b-3xl".to_owned(), "border-bottom-right-radius: 1.5rem;order-bottom-left-radius: 1.5rem;".to_owned()); /* 24px */
    let _ = border_radius.insert("rounded-b-full".to_owned(), "border-bottom-right-radius: 9999px;border-bottom-left-radius: 9999px;".to_owned());
    let _ = border_radius.insert("rounded-l-none".to_owned(), "border-top-left-radius: 0px;border-bottom-left-radius: 0px;".to_owned());
    let _ = border_radius.insert("rounded-l-sm".to_owned(), "border-top-left-radius: 0.125rem;order-bottom-left-radius: 0.125rem;".to_owned()); /* 2px */
    let _ = border_radius.insert("rounded-l".to_owned(), "border-top-left-radius: 0.25rem;order-bottom-left-radius: 0.25rem;".to_owned()); /* 4px */
    let _ = border_radius.insert("rounded-l-md".to_owned(), "border-top-left-radius: 0.375rem;order-bottom-left-radius: 0.375rem;".to_owned()); /* 6px */
    let _ = border_radius.insert("rounded-l-lg".to_owned(), "border-top-left-radius: 0.5rem;order-bottom-left-radius: 0.5rem;".to_owned()); /* 8px */
    let _ = border_radius.insert("rounded-l-xl".to_owned(), "border-top-left-radius: 0.75rem;order-bottom-left-radius: 0.75rem;".to_owned()); /* 12px */
    let _ = border_radius.insert("rounded-l-2xl".to_owned(), "border-top-left-radius: 1rem;order-bottom-left-radius: 1rem;".to_owned()); /* 16px */
    let _ = border_radius.insert("rounded-l-3xl".to_owned(), "border-top-left-radius: 1.5rem;order-bottom-left-radius: 1.5rem;".to_owned()); /* 24px */
    let _ = border_radius.insert("rounded-l-full".to_owned(), "border-top-left-radius: 9999px;border-bottom-left-radius: 9999px;".to_owned());
    let _ = border_radius.insert("rounded-tl-none".to_owned(), "border-top-left-radius: 0px;".to_owned());
    let _ = border_radius.insert("rounded-tl-sm".to_owned(), "border-top-left-radius: 0.125rem;".to_owned()); /* 2px */
    let _ = border_radius.insert("rounded-tl".to_owned(), "border-top-left-radius: 0.25rem;".to_owned()); /* 4px */
    let _ = border_radius.insert("rounded-tl-md".to_owned(), "border-top-left-radius: 0.375rem;".to_owned()); /* 6px */
    let _ = border_radius.insert("rounded-tl-lg".to_owned(), "border-top-left-radius: 0.5rem;".to_owned()); /* 8px */
    let _ = border_radius.insert("rounded-tl-xl".to_owned(), "border-top-left-radius: 0.75rem;".to_owned()); /* 12px */
    let _ = border_radius.insert("rounded-tl-2xl".to_owned(), "border-top-left-radius: 1rem;".to_owned()); /* 16px */
    let _ = border_radius.insert("rounded-tl-3xl".to_owned(), "border-top-left-radius: 1.5rem;".to_owned()); /* 24px */
    let _ = border_radius.insert("rounded-tl-full".to_owned(), "border-top-left-radius: 9999px;".to_owned());
    let _ = border_radius.insert("rounded-tr-none".to_owned(), "border-top-right-radius: 0px;".to_owned());
    let _ = border_radius.insert("rounded-tr-sm".to_owned(), "border-top-right-radius: 0.125rem;".to_owned()); /* 2px */
    let _ = border_radius.insert("rounded-tr".to_owned(), "border-top-right-radius: 0.25rem;".to_owned()); /* 4px */
    let _ = border_radius.insert("rounded-tr-md".to_owned(), "border-top-right-radius: 0.375rem;".to_owned()); /* 6px */
    let _ = border_radius.insert("rounded-tr-lg".to_owned(), "border-top-right-radius: 0.5rem;".to_owned()); /* 8px */
    let _ = border_radius.insert("rounded-tr-xl".to_owned(), "border-top-right-radius: 0.75rem;".to_owned()); /* 12px */
    let _ = border_radius.insert("rounded-tr-2xl".to_owned(), "border-top-right-radius: 1rem;".to_owned()); /* 16px */
    let _ = border_radius.insert("rounded-tr-3xl".to_owned(), "border-top-right-radius: 1.5rem;".to_owned()); /* 24px */
    let _ = border_radius.insert("rounded-tr-full".to_owned(), "border-top-right-radius: 9999px;".to_owned());
    let _ = border_radius.insert("rounded-br-none".to_owned(), "border-bottom-right-radius: 0px;".to_owned());
    let _ = border_radius.insert("rounded-br-sm".to_owned(), "border-bottom-right-radius: 0.125rem;".to_owned()); /* 2px */
    let _ = border_radius.insert("rounded-br".to_owned(), "border-bottom-right-radius: 0.25rem;".to_owned()); /* 4px */
    let _ = border_radius.insert("rounded-br-md".to_owned(), "border-bottom-right-radius: 0.375rem;".to_owned()); /* 6px */
    let _ = border_radius.insert("rounded-br-lg".to_owned(), "border-bottom-right-radius: 0.5rem;".to_owned()); /* 8px */
    let _ = border_radius.insert("rounded-br-xl".to_owned(), "border-bottom-right-radius: 0.75rem;".to_owned()); /* 12px */
    let _ = border_radius.insert("rounded-br-2xl".to_owned(), "border-bottom-right-radius: 1rem;".to_owned()); /* 16px */
    let _ = border_radius.insert("rounded-br-3xl".to_owned(), "border-bottom-right-radius: 1.5rem;".to_owned()); /* 24px */
    let _ = border_radius.insert("rounded-br-full".to_owned(), "border-bottom-right-radius: 9999px;".to_owned());
    let _ = border_radius.insert("rounded-bl-none".to_owned(), "border-bottom-left-radius: 0px;".to_owned());
    let _ = border_radius.insert("rounded-bl-sm".to_owned(), "border-bottom-left-radius: 0.125rem;".to_owned()); /* 2px */
    let _ = border_radius.insert("rounded-bl".to_owned(), "border-bottom-left-radius: 0.25rem;".to_owned()); /* 4px */
    let _ = border_radius.insert("rounded-bl-md".to_owned(), "border-bottom-left-radius: 0.375rem;".to_owned()); /* 6px */
    let _ = border_radius.insert("rounded-bl-lg".to_owned(), "border-bottom-left-radius: 0.5rem;".to_owned()); /* 8px */
    let _ = border_radius.insert("rounded-bl-xl".to_owned(), "border-bottom-left-radius: 0.75rem;".to_owned()); /* 12px */
    let _ = border_radius.insert("rounded-bl-2xl".to_owned(), "border-bottom-left-radius: 1rem;".to_owned()); /* 16px */
    let _ = border_radius.insert("rounded-bl-3xl".to_owned(), "border-bottom-left-radius: 1.5rem;".to_owned()); /* 24px */
    let _ = border_radius.insert("rounded-bl-full".to_owned(), "border-bottom-left-radius: 9999px;".to_owned());

    border_radius
}