use std::collections::HashMap;


pub(crate) fn width() -> HashMap<String, String> {
    let mut width = HashMap::new();
    let _ = width.insert("w-0".to_owned(), "width: 0px;".to_owned());
    let _ = width.insert("w-px".to_owned(), "width: 1px;".to_owned());
    let _ = width.insert("w-0.5".to_owned(), "width: 0.125rem;".to_owned()); /* 2px */
    let _ = width.insert("w-1".to_owned(), "width: 0.25rem;".to_owned()); /* 4px */
    let _ = width.insert("w-1.5".to_owned(), "width: 0.375rem;".to_owned()); /* 6px */
    let _ = width.insert("w-2".to_owned(), "width: 0.5rem;".to_owned()); /* 8px */
    let _ = width.insert("w-2.5".to_owned(), "width: 0.625rem;".to_owned()); /* 10px */
    let _ = width.insert("w-3".to_owned(), "width: 0.75rem;".to_owned()); /* 12px */
    let _ = width.insert("w-3.5".to_owned(), "width: 0.875rem;".to_owned()); /* 14px */
    let _ = width.insert("w-4".to_owned(), "width: 1rem;".to_owned()); /* 16px */
    let _ = width.insert("w-5".to_owned(), "width: 1.25rem;".to_owned()); /* 20px */
    let _ = width.insert("w-6".to_owned(), "width: 1.5rem;".to_owned()); /* 24px */
    let _ = width.insert("w-7".to_owned(), "width: 1.75rem;".to_owned()); /* 28px */
    let _ = width.insert("w-8".to_owned(), "width: 2rem;".to_owned()); /* 32px */
    let _ = width.insert("w-9".to_owned(), "width: 2.25rem;".to_owned()); /* 36px */
    let _ = width.insert("w-10".to_owned(), "width: 2.5rem;".to_owned()); /* 40px */
    let _ = width.insert("w-11".to_owned(), "width: 2.75rem;".to_owned()); /* 44px */
    let _ = width.insert("w-12".to_owned(), "width: 3rem;".to_owned()); /* 48px */
    let _ = width.insert("w-14".to_owned(), "width: 3.5rem;".to_owned()); /* 56px */
    let _ = width.insert("w-16".to_owned(), "width: 4rem;".to_owned()); /* 64px */
    let _ = width.insert("w-20".to_owned(), "width: 5rem;".to_owned()); /* 80px */
    let _ = width.insert("w-24".to_owned(), "width: 6rem;".to_owned()); /* 96px */
    let _ = width.insert("w-28".to_owned(), "width: 7rem;".to_owned()); /* 112px */
    let _ = width.insert("w-32".to_owned(), "width: 8rem;".to_owned()); /* 128px */
    let _ = width.insert("w-36".to_owned(), "width: 9rem;".to_owned()); /* 144px */
    let _ = width.insert("w-40".to_owned(), "width: 10rem;".to_owned()); /* 160px */
    let _ = width.insert("w-44".to_owned(), "width: 11rem;".to_owned()); /* 176px */
    let _ = width.insert("w-48".to_owned(), "width: 12rem;".to_owned()); /* 192px */
    let _ = width.insert("w-52".to_owned(), "width: 13rem;".to_owned()); /* 208px */
    let _ = width.insert("w-56".to_owned(), "width: 14rem;".to_owned()); /* 224px */
    let _ = width.insert("w-60".to_owned(), "width: 15rem;".to_owned()); /* 240px */
    let _ = width.insert("w-64".to_owned(), "width: 16rem;".to_owned()); /* 256px */
    let _ = width.insert("w-72".to_owned(), "width: 18rem;".to_owned()); /* 288px */
    let _ = width.insert("w-80".to_owned(), "width: 20rem;".to_owned()); /* 320px */
    let _ = width.insert("w-96".to_owned(), "width: 24rem;".to_owned()); /* 384px */
    let _ = width.insert("w-1/2".to_owned(), "width: 50%;".to_owned());
    let _ = width.insert("w-1/3".to_owned(), "width: 33.333333%;".to_owned());
    let _ = width.insert("w-2/3".to_owned(), "width: 66.666667%;".to_owned());
    let _ = width.insert("w-1/4".to_owned(), "width: 25%;".to_owned());
    let _ = width.insert("w-2/4".to_owned(), "width: 50%;".to_owned());
    let _ = width.insert("w-3/4".to_owned(), "width: 75%;".to_owned());
    let _ = width.insert("w-1/5".to_owned(), "width: 20%;".to_owned());
    let _ = width.insert("w-2/5".to_owned(), "width: 40%;".to_owned());
    let _ = width.insert("w-3/5".to_owned(), "width: 60%;".to_owned());
    let _ = width.insert("w-4/5".to_owned(), "width: 80%;".to_owned());
    let _ = width.insert("w-1/6".to_owned(), "width: 16.666667%;".to_owned());
    let _ = width.insert("w-2/6".to_owned(), "width: 33.333333%;".to_owned());
    let _ = width.insert("w-3/6".to_owned(), "width: 50%;".to_owned());
    let _ = width.insert("w-4/6".to_owned(), "width: 66.666667%;".to_owned());
    let _ = width.insert("w-5/6".to_owned(), "width: 83.333333%;".to_owned());
    let _ = width.insert("w-1/12".to_owned(), "width: 8.333333%;".to_owned());
    let _ = width.insert("w-2/12".to_owned(), "width: 16.666667%;".to_owned());
    let _ = width.insert("w-3/12".to_owned(), "width: 25%;".to_owned());
    let _ = width.insert("w-4/12".to_owned(), "width: 33.333333%;".to_owned());
    let _ = width.insert("w-5/12".to_owned(), "width: 41.666667%;".to_owned());
    let _ = width.insert("w-6/12".to_owned(), "width: 50%;".to_owned());
    let _ = width.insert("w-7/12".to_owned(), "width: 58.333333%;".to_owned());
    let _ = width.insert("w-8/12".to_owned(), "width: 66.666667%;".to_owned());
    let _ = width.insert("w-9/12".to_owned(), "width: 75%;".to_owned());
    let _ = width.insert("w-10/12".to_owned(), "width: 83.333333%;".to_owned());
    let _ = width.insert("w-11/12".to_owned(), "width: 91.666667%;".to_owned());
    let _ = width.insert("w-full".to_owned(), "width: 100%;".to_owned());
    let _ = width.insert("vw-10".to_owned(), "width:  10vw;".to_owned());
    let _ = width.insert("vw-20".to_owned(), "width:  20vw;".to_owned());
    let _ = width.insert("vw-25".to_owned(), "width:  25vw;".to_owned());
    let _ = width.insert("vw-30".to_owned(), "width:  30vw;".to_owned());
    let _ = width.insert("vw-40".to_owned(), "width:  40vw;".to_owned());
    let _ = width.insert("vw-50".to_owned(), "width:  50vw;".to_owned());
    let _ = width.insert("vw-60".to_owned(), "width:  60vw;".to_owned());
    let _ = width.insert("vw-70".to_owned(), "width:  70vw;".to_owned());
    let _ = width.insert("vw-75".to_owned(), "width:  75vw;".to_owned());
    let _ = width.insert("vw-80".to_owned(), "width:  80vw;".to_owned());
    let _ = width.insert("vw-90".to_owned(), "width:  90vw;".to_owned());
    let _ = width.insert("vw-100".to_owned(), "width: 100vw;".to_owned());
    let _ = width.insert("w-min".to_owned(), "width: min-content;".to_owned());
    let _ = width.insert("w-max".to_owned(), "width: max-content;".to_owned());
    let _ = width.insert("w-fit".to_owned(), "width: fit-content;".to_owned());
    let _ = width.insert("w-auto".to_owned(), "width: auto;".to_owned());
    let _ = width.insert("w-inherit".to_owned(), "width: inherit;".to_owned());
    let _ = width.insert("w-third".to_owned(), "width: calc(100% / 3);".to_owned());
    let _ = width.insert("w-two-thirds".to_owned(), "width: calc(100% / 1.5);".to_owned());

    width
}